### ISSUE TITLE
Steam sale

### ISSUE THREAD

**Issue by DRB02** [ge-ku/AutoJoin-for-SteamGifts#35]
Could you please add the steam sale function auto join again. Or is it chrome only because this is the first steamsale Im on firefox

**Comment by ge-ku** [comment]
It's Chrome only because it uses a sketchy method of injecting script into the page and it doesn't pass Firefox moderation (or at least didn't pass last time I tried, before automated reviews).

You can create a bookmarklet using this code instead:
`javascript:void%20function(){var%20e,o=function(i){e=ShowBlockingWaitDialog(%22Exploring%20queue...%22,%22Generating%20new%20discovery%20queue%20%23%22+%20++i),jQuery.post(%22//store.steampowered.com/explore/generatenewdiscoveryqueue%22,{sessionid:g_sessionID,queuetype:0}).done(function(n){for(var%20u,a=[],r=0,s=0;s%3Cn.queue.length;s++){var%20t=jQuery.post(%22//store.steampowered.com/app/10%22,{appid_to_clear_from_queue:n.queue[s],sessionid:g_sessionID});t.done(function(){u||(e.Dismiss(),e=ShowBlockingWaitDialog(%22Exploring%20the%20queue...%22,%22Request%20%22+%20++r+%22%20of%20%22+n.queue.length))}),t.fail(function(){u=!0,e.Dismiss(),e=ShowConfirmDialog(%22Error%22,%22Failed%20to%20clear%20queue%20item%20%23%22+%20++r,%22Try%20again%22).done(function(){o(i-1)})}),a.push(t)}jQuery.when.apply(jQuery,a).done(function(){e.Dismiss(),3%3Ei%3Fo(i):e=ShowConfirmDialog(%22Done%22,%22Queue%20has%20been%20explored%20%22+i+%22%20times%22,%22Reload%20the%20page%22).done(function(){ShowBlockingWaitDialog(%22Reloading%20the%20page%22),window.location.reload()})})}).fail(function(){e.Dismiss(),e=ShowConfirmDialog(%22Error%22,%22Failed%20to%20generate%20new%20queue%20%23%22+i,%22Try%20again%22).done(function(){o(i-1)})})};o(0)}();`

**Comment by DRB02** [comment]
You are amazing! Thank you!
