### ISSUE TITLE
Not working with ESGST

### ISSUE THREAD

**Issue by vaibhavhrt** [ge-ku/AutoJoin-for-SteamGifts#42]
Stopped working alongside the userscript [gsrafael01/ESGST](https://github.com/gsrafael01/ESGST)
Used to work before.
The Join button, win chance etc. doesn't show.
Inspecting the background page of extension show my points etc in console, so extensive is active but there is no UI change.

**Comment by ge-ku** [comment]
Hello, there were no updates to this extension for a very long time, so it's something to do with extension you linked or with Steamgifts itself. Can you please check console (Ctrl+Shift+J) for any errors while you're on Steamgifts?

**Comment by vaibhavhrt** [comment]
Actually there are, should i just add the screenshot, or is there a way to export it as text

**Comment by vaibhavhrt** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/22582828/50838142-55a48680-1383-11e9-8146-d29aeed7e085.png)

**Comment by ge-ku** [comment]
Looks like with default settings this extension swaps number of copies and cost of giveaway in heading. So `Lovely Planet (2 Copies) (6P)` becomes `Lovely Planet (6P) (2 Copies)`. You can go into settings of that extension (Element Ordering -> Giveaway Heading) and swap Copies with Points (so that Copies are before Points), this way it should work.

**Comment by vaibhavhrt** [comment]
That it solved it.
Here is a screenshot of what ESGST settings should look like after you change is for someone else who run into this problem.
![image](https://user-images.githubusercontent.com/22582828/50839954-766edb00-1387-11e9-975d-79c978559b7c.png)
